//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Log.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class it_log
    {
        public int it_log_id { get; set; }
        public string name { get; set; }
        public string office { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public string service_request { get; set; }
        public Nullable<int> it_personnel_id { get; set; }
    
        public virtual it_personnel it_personnel { get; set; }
    }
}
